#############################################################################
# Makefile for building: bulk-club-project-cs1c.app/Contents/MacOS/bulk-club-project-cs1c
# Generated by qmake (3.1) (Qt 6.5.0)
# Project:  bulk-club-project-cs1c.pro
# Template: app
# Command: /Users/ssmith/Qt/6.5.0/macos/bin/qmake -o Makefile bulk-club-project-cs1c.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I../Qt/6.5.0/macos/lib/QtGui.framework/Headers -I../Qt/6.5.0/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../Qt/6.5.0/macos/mkspecs/macx-clang -F/Users/ssmith/Qt/6.5.0/macos/lib
QMAKE         = /Users/ssmith/Qt/6.5.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/ssmith/Qt/6.5.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/ssmith/Qt/6.5.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = bulk-club-project-cs1c1.0.0
DISTDIR = /Users/ssmith/bulk-project/.tmp/bulk-club-project-cs1c1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/ssmith/Qt/6.5.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/ssmith/Qt/6.5.0/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		admin.cpp \
		adminlogin.cpp \
		adminmainpage.cpp \
		memberinfo.cpp moc_mainwindow.cpp \
		moc_adminlogin.cpp \
		moc_admin.cpp \
		moc_adminmainpage.cpp
OBJECTS       = main.o \
		mainwindow.o \
		admin.o \
		adminlogin.o \
		adminmainpage.o \
		memberinfo.o \
		moc_mainwindow.o \
		moc_adminlogin.o \
		moc_admin.o \
		moc_adminmainpage.o
DIST          = ../Qt/6.5.0/macos/mkspecs/features/spec_pre.prf \
		../Qt/6.5.0/macos/mkspecs/features/device_config.prf \
		../Qt/6.5.0/macos/mkspecs/common/unix.conf \
		../Qt/6.5.0/macos/mkspecs/common/mac.conf \
		../Qt/6.5.0/macos/mkspecs/common/macx.conf \
		../Qt/6.5.0/macos/mkspecs/common/sanitize.conf \
		../Qt/6.5.0/macos/mkspecs/common/gcc-base.conf \
		../Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf \
		../Qt/6.5.0/macos/mkspecs/common/clang.conf \
		../Qt/6.5.0/macos/mkspecs/common/clang-mac.conf \
		../Qt/6.5.0/macos/mkspecs/qconfig.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Qt/6.5.0/macos/mkspecs/features/qt_functions.prf \
		../Qt/6.5.0/macos/mkspecs/features/qt_config.prf \
		../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf \
		../Qt/6.5.0/macos/mkspecs/features/spec_post.prf \
		../Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf \
		../Qt/6.5.0/macos/mkspecs/features/toolchain.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf \
		../Qt/6.5.0/macos/mkspecs/features/default_pre.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf \
		../Qt/6.5.0/macos/mkspecs/features/resolve_config.prf \
		../Qt/6.5.0/macos/mkspecs/features/default_post.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf \
		../Qt/6.5.0/macos/mkspecs/features/qml_debug.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/mac.prf \
		../Qt/6.5.0/macos/mkspecs/features/warn_on.prf \
		../Qt/6.5.0/macos/mkspecs/features/permissions.prf \
		../Qt/6.5.0/macos/mkspecs/features/qt.prf \
		../Qt/6.5.0/macos/mkspecs/features/resources_functions.prf \
		../Qt/6.5.0/macos/mkspecs/features/resources.prf \
		../Qt/6.5.0/macos/mkspecs/features/moc.prf \
		../Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf \
		../Qt/6.5.0/macos/mkspecs/features/uic.prf \
		../Qt/6.5.0/macos/mkspecs/features/unix/thread.prf \
		../Qt/6.5.0/macos/mkspecs/features/qmake_use.prf \
		../Qt/6.5.0/macos/mkspecs/features/file_copies.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/rez.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf \
		../Qt/6.5.0/macos/mkspecs/features/exceptions.prf \
		../Qt/6.5.0/macos/mkspecs/features/yacc.prf \
		../Qt/6.5.0/macos/mkspecs/features/lex.prf \
		bulk-club-project-cs1c.pro mainwindow.h \
		adminlogin.h \
		admin.h \
		adminmainpage.h \
		member.h \
		memberinfo.cpp main.cpp \
		mainwindow.cpp \
		admin.cpp \
		adminlogin.cpp \
		adminmainpage.cpp \
		memberinfo.cpp
QMAKE_TARGET  = bulk-club-project-cs1c
DESTDIR       = 
TARGET        = bulk-club-project-cs1c.app/Contents/MacOS/bulk-club-project-cs1c

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/ssmith/bulk-project/bulk-club-project-cs1c.pro


include /Users/ssmith/Qt/6.5.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

bulk-club-project-cs1c.app/Contents/MacOS/bulk-club-project-cs1c: ui_mainwindow.h ui_adminlogin.h ui_adminmainpage.h ui_memberinfo.h ui_admin.h $(OBJECTS)  
	@test -d bulk-club-project-cs1c.app/Contents/MacOS/ || mkdir -p bulk-club-project-cs1c.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bulk-club-project-cs1c.pro ../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf ../Qt/6.5.0/macos/mkspecs/features/spec_pre.prf \
		../Qt/6.5.0/macos/mkspecs/features/device_config.prf \
		../Qt/6.5.0/macos/mkspecs/common/unix.conf \
		../Qt/6.5.0/macos/mkspecs/common/mac.conf \
		../Qt/6.5.0/macos/mkspecs/common/macx.conf \
		../Qt/6.5.0/macos/mkspecs/common/sanitize.conf \
		../Qt/6.5.0/macos/mkspecs/common/gcc-base.conf \
		../Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf \
		../Qt/6.5.0/macos/mkspecs/common/clang.conf \
		../Qt/6.5.0/macos/mkspecs/common/clang-mac.conf \
		../Qt/6.5.0/macos/mkspecs/qconfig.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Qt/6.5.0/macos/mkspecs/features/qt_functions.prf \
		../Qt/6.5.0/macos/mkspecs/features/qt_config.prf \
		../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf \
		../Qt/6.5.0/macos/mkspecs/features/spec_post.prf \
		../Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf \
		../Qt/6.5.0/macos/mkspecs/features/toolchain.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf \
		../Qt/6.5.0/macos/mkspecs/features/default_pre.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf \
		../Qt/6.5.0/macos/mkspecs/features/resolve_config.prf \
		../Qt/6.5.0/macos/mkspecs/features/default_post.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf \
		../Qt/6.5.0/macos/mkspecs/features/qml_debug.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/mac.prf \
		../Qt/6.5.0/macos/mkspecs/features/warn_on.prf \
		../Qt/6.5.0/macos/mkspecs/features/permissions.prf \
		../Qt/6.5.0/macos/mkspecs/features/qt.prf \
		../Qt/6.5.0/macos/mkspecs/features/resources_functions.prf \
		../Qt/6.5.0/macos/mkspecs/features/resources.prf \
		../Qt/6.5.0/macos/mkspecs/features/moc.prf \
		../Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf \
		../Qt/6.5.0/macos/mkspecs/features/uic.prf \
		../Qt/6.5.0/macos/mkspecs/features/unix/thread.prf \
		../Qt/6.5.0/macos/mkspecs/features/qmake_use.prf \
		../Qt/6.5.0/macos/mkspecs/features/file_copies.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/rez.prf \
		../Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf \
		../Qt/6.5.0/macos/mkspecs/features/exceptions.prf \
		../Qt/6.5.0/macos/mkspecs/features/yacc.prf \
		../Qt/6.5.0/macos/mkspecs/features/lex.prf \
		bulk-club-project-cs1c.pro \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../Qt/6.5.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../Qt/6.5.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile bulk-club-project-cs1c.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../Qt/6.5.0/macos/mkspecs/features/spec_pre.prf:
../Qt/6.5.0/macos/mkspecs/features/device_config.prf:
../Qt/6.5.0/macos/mkspecs/common/unix.conf:
../Qt/6.5.0/macos/mkspecs/common/mac.conf:
../Qt/6.5.0/macos/mkspecs/common/macx.conf:
../Qt/6.5.0/macos/mkspecs/common/sanitize.conf:
../Qt/6.5.0/macos/mkspecs/common/gcc-base.conf:
../Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf:
../Qt/6.5.0/macos/mkspecs/common/clang.conf:
../Qt/6.5.0/macos/mkspecs/common/clang-mac.conf:
../Qt/6.5.0/macos/mkspecs/qconfig.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../Qt/6.5.0/macos/mkspecs/features/qt_functions.prf:
../Qt/6.5.0/macos/mkspecs/features/qt_config.prf:
../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf:
../Qt/6.5.0/macos/mkspecs/features/spec_post.prf:
../Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf:
../Qt/6.5.0/macos/mkspecs/features/toolchain.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf:
../Qt/6.5.0/macos/mkspecs/features/default_pre.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf:
../Qt/6.5.0/macos/mkspecs/features/resolve_config.prf:
../Qt/6.5.0/macos/mkspecs/features/default_post.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf:
../Qt/6.5.0/macos/mkspecs/features/qml_debug.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/mac.prf:
../Qt/6.5.0/macos/mkspecs/features/warn_on.prf:
../Qt/6.5.0/macos/mkspecs/features/permissions.prf:
../Qt/6.5.0/macos/mkspecs/features/qt.prf:
../Qt/6.5.0/macos/mkspecs/features/resources_functions.prf:
../Qt/6.5.0/macos/mkspecs/features/resources.prf:
../Qt/6.5.0/macos/mkspecs/features/moc.prf:
../Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf:
../Qt/6.5.0/macos/mkspecs/features/uic.prf:
../Qt/6.5.0/macos/mkspecs/features/unix/thread.prf:
../Qt/6.5.0/macos/mkspecs/features/qmake_use.prf:
../Qt/6.5.0/macos/mkspecs/features/file_copies.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/rez.prf:
../Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf:
../Qt/6.5.0/macos/mkspecs/features/exceptions.prf:
../Qt/6.5.0/macos/mkspecs/features/yacc.prf:
../Qt/6.5.0/macos/mkspecs/features/lex.prf:
bulk-club-project-cs1c.pro:
../Qt/6.5.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../Qt/6.5.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../Qt/6.5.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile bulk-club-project-cs1c.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

bulk-club-project-cs1c.app/Contents/PkgInfo: 
	@test -d bulk-club-project-cs1c.app/Contents || mkdir -p bulk-club-project-cs1c.app/Contents
	@$(DEL_FILE) bulk-club-project-cs1c.app/Contents/PkgInfo
	@echo "APPL????" > bulk-club-project-cs1c.app/Contents/PkgInfo
bulk-club-project-cs1c.app/Contents/Resources/empty.lproj: 
	@test -d bulk-club-project-cs1c.app/Contents/Resources || mkdir -p bulk-club-project-cs1c.app/Contents/Resources
	@touch bulk-club-project-cs1c.app/Contents/Resources/empty.lproj
	
bulk-club-project-cs1c.app/Contents/Info.plist: 
	@test -d bulk-club-project-cs1c.app/Contents || mkdir -p bulk-club-project-cs1c.app/Contents
	@$(DEL_FILE) bulk-club-project-cs1c.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../Qt/6.5.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.bulk-club-project-cs1c,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.bulk-club-project-cs1c,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,bulk-club-project-cs1c,g" -e "s,@LIBRARY@,bulk-club-project-cs1c,g" -e "s,\$${EXECUTABLE_NAME},bulk-club-project-cs1c,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >bulk-club-project-cs1c.app/Contents/Info.plist

all: Makefile \
		bulk-club-project-cs1c.app/Contents/PkgInfo \
		bulk-club-project-cs1c.app/Contents/Resources/empty.lproj \
		bulk-club-project-cs1c.app/Contents/Info.plist bulk-club-project-cs1c.app/Contents/MacOS/bulk-club-project-cs1c

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h adminlogin.h admin.h adminmainpage.h member.h memberinfo.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp admin.cpp adminlogin.cpp adminmainpage.cpp memberinfo.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui adminlogin.ui adminmainpage.ui memberinfo.ui admin.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r bulk-club-project-cs1c.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_adminlogin.cpp moc_admin.cpp moc_adminmainpage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_adminlogin.cpp moc_admin.cpp moc_adminmainpage.cpp
moc_mainwindow.cpp: mainwindow.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/6.5.0/macos/libexec/moc
	/Users/ssmith/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/ssmith/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/ssmith/bulk-project -I/Users/ssmith/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/ssmith/Qt/6.5.0/macos/lib mainwindow.h -o moc_mainwindow.cpp

moc_adminlogin.cpp: adminlogin.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		adminmainpage.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		memberinfo.h \
		sales.h \
		../Qt/6.5.0/macos/libexec/moc
	/Users/ssmith/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/ssmith/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/ssmith/bulk-project -I/Users/ssmith/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/ssmith/Qt/6.5.0/macos/lib adminlogin.h -o moc_adminlogin.cpp

moc_admin.cpp: admin.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		adminmainpage.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		memberinfo.h \
		sales.h \
		../Qt/6.5.0/macos/libexec/moc
	/Users/ssmith/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/ssmith/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/ssmith/bulk-project -I/Users/ssmith/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/ssmith/Qt/6.5.0/macos/lib admin.h -o moc_admin.cpp

moc_adminmainpage.cpp: adminmainpage.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		memberinfo.h \
		sales.h \
		../Qt/6.5.0/macos/libexec/moc
	/Users/ssmith/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/ssmith/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/ssmith/bulk-project -I/Users/ssmith/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/ssmith/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/ssmith/Qt/6.5.0/macos/lib adminmainpage.h -o moc_adminmainpage.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_adminlogin.h ui_adminmainpage.h ui_memberinfo.h ui_admin.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_adminlogin.h ui_adminmainpage.h ui_memberinfo.h ui_admin.h
ui_mainwindow.h: mainwindow.ui \
		../Qt/6.5.0/macos/libexec/uic
	/Users/ssmith/Qt/6.5.0/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

ui_adminlogin.h: adminlogin.ui \
		../Qt/6.5.0/macos/libexec/uic
	/Users/ssmith/Qt/6.5.0/macos/libexec/uic adminlogin.ui -o ui_adminlogin.h

ui_adminmainpage.h: adminmainpage.ui \
		../Qt/6.5.0/macos/libexec/uic
	/Users/ssmith/Qt/6.5.0/macos/libexec/uic adminmainpage.ui -o ui_adminmainpage.h

ui_memberinfo.h: memberinfo.ui \
		../Qt/6.5.0/macos/libexec/uic
	/Users/ssmith/Qt/6.5.0/macos/libexec/uic memberinfo.ui -o ui_memberinfo.h

ui_admin.h: admin.ui \
		../Qt/6.5.0/macos/libexec/uic
	/Users/ssmith/Qt/6.5.0/macos/libexec/uic admin.ui -o ui_admin.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

admin.o: admin.cpp admin.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		adminmainpage.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		memberinfo.h \
		sales.h \
		ui_admin.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admin.o admin.cpp

adminlogin.o: adminlogin.cpp admin.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		adminmainpage.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		memberinfo.h \
		sales.h \
		ui_adminlogin.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminlogin.o adminlogin.cpp

adminmainpage.o: adminmainpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminmainpage.o adminmainpage.cpp

memberinfo.o: memberinfo.cpp memberinfo.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_memberinfo.h \
		../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QFile \
		../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qfile.h \
		../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTextStream \
		../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtextstream.h \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memberinfo.o memberinfo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_adminlogin.o: moc_adminlogin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminlogin.o moc_adminlogin.cpp

moc_admin.o: moc_admin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admin.o moc_admin.cpp

moc_adminmainpage.o: moc_adminmainpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminmainpage.o moc_adminmainpage.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/bulk-club-project-cs1c/bin || mkdir -p $(INSTALL_ROOT)/opt/bulk-club-project-cs1c/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/bulk-club-project-cs1c/bin/bulk-club-project-cs1c.app
	
	$(QINSTALL) bulk-club-project-cs1c.app $(INSTALL_ROOT)/opt/bulk-club-project-cs1c/bin/bulk-club-project-cs1c.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/bulk-club-project-cs1c/bin/bulk-club-project-cs1c.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/bulk-club-project-cs1c/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

